### ISSUE TITLE
Tentei clonar esse site e deu esse erro

### ISSUE THREAD

**Issue by williank** [ZKAW/website-cloner#2]
https://emergencia190.com/

Traceback (most recent call last):
  File "/home/kevenis/Emergencia/site_clone/app.py", line 234, in <module>
    extractor.run()
  File "/home/kevenis/Emergencia/site_clone/app.py", line 37, in run
    self.save_files(self.scraped_urls)
  File "/home/kevenis/Emergencia/site_clone/app.py", line 216, in save_files
    self.download_file(url, output_path)
  File "/home/kevenis/Emergencia/site_clone/app.py", line 204, in download_file
    with open(output_path, "wb") as file:
NotADirectoryError: [Errno 20] Not a directory: '/home/kevenis/Emergencia/site_clone/www.emergencia190.com/blog/pistaquente/8-qual-prazo-maximo-o-processo-de-arma-pode-durar.html'

**Comment by Jiroun** [comment]
same problem
